# ============================================================
# ROS-GZ Bridge — COSMUS_gz2 — 1 avião independentes
# Gazebo Harmonic + ROS 2 Jazzy
# ============================================================
# Clock
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Odometria
- ros_topic_name: "/plane00/odometry"
  gz_topic_name: "/model/plane00/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# IMU
- ros_topic_name: "/plane00/imu"
  gz_topic_name: "/model/plane00/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# NavSat
- ros_topic_name: "/plane00/navsat"
  gz_topic_name: "/model/plane00/navsat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS

# Throttle (rotor_puller_joint) – ainda via cmd_vel
- ros_topic_name: "/plane00/cmd_throttle"
  gz_topic_name: "/model/plane00/joint/rotor_puller_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: false

# Superfícies de controle (caso já queira testar)
- ros_topic_name: "/plane00/cmd_elevator"
  gz_topic_name: "/model/plane00/joint/elevator_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/plane00/cmd_left_elevon"
  gz_topic_name: "/model/plane00/joint/left_elevon_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/plane00/cmd_right_elevon"
  gz_topic_name: "/model/plane00/joint/right_elevon_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/plane00/cmd_rudder"
  gz_topic_name: "/model/plane00/joint/rudder_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

